# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JDToolsModuleDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for JDToolsModuleDemo

  pod 'JDToolsModule', :path => "../JDToolsModule.podspec"

  target 'JDToolsModuleDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JDToolsModuleDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
